Running version of plugin

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,61 +1,46 @@
-# Continuous integration testing for ChRIS Plugin.
+# Automatically build multi-architectural tagged container images and push them to DockerHub
 # https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds
 #
-# - automatically run pytest
-# - on push to main, build and push container images as ":latest"
-# - on release, build and push container image with tag and
-#   upload plugin description to https://chrisstore.co
+# - targeted platforms: x86_64, PowerPC64, ARM64
+# - master is built as fnndsc/pl-unirep_analysis:latest
+# - tagged commits are built as fnndsc/pl-unirep_analysis:<tag>
+# - tagged commits are also uploaded to chrisstore.co
+#
+# In order to use this workflow, see
+# https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds#steps-to-enable
 
-name: build
+name: ci
 
 on:
   push:
-    branches: [ main ]
+    # we have to guess what the name of the default branch is
+    branches: [ master, main, trunk ]
+    tags: [ '**' ]
   pull_request:
-    branches: [ main ]
-  release:
-    types: [ published ]
+    branches: [ master, main, trunk ]
 
 jobs:
   test:
-    name: Unit tests
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
-      - uses: docker/setup-buildx-action@v1
-      - name: Cache Docker layers
-        uses: actions/cache@v2
-        with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
-      - name: Build
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          load: true
-          push: false
-          tags: "localhost/local/app:latest"
-          cache-from: type=local,src=/tmp/.buildx-cache
-          cache-to: type=local,dest=/tmp/.buildx-cache
-      - name: Install testing dependencies
-        run: |
-          docker run --name=install_test localhost/local/app:latest pip install pytest
-          docker commit install_test localhost/local/app:tester
-          docker rm install_test
-      - name: Run pytest
-        run: |
-          docker run -v "$GITHUB_WORKSPACE:/app:ro" -w /app localhost/local/app:tester \
-            pytest -o cache_dir=/tmp/pytest
+      - name: build
+        run: docker build -t "${GITHUB_REPOSITORY,,}" .
+      - name: nose tests
+        run: docker run "${GITHUB_REPOSITORY,,}" nosetests
 
-  build:
-    name: Build
-    needs: [ test ]  # tests must pass before build
+  publish:
     if: github.event_name == 'push' || github.event_name == 'release'
     runs-on: ubuntu-20.04
 
-    # A local registry helps us reuse the built image between steps
+    # we want to both push the build to DockerHub, but also
+    # keep a local copy so that we can run
+    #
+    #     docker run fnndsc/pl-app app --json > App.json
+    #
+    # buildx currently does not support multiple output locations,
+    # neither can multi-architectural builds be loaded into docker.
+    # Here we use a local registry to cache the build.
     services:
       registry:
         image: registry:2
@@ -67,7 +52,7 @@ jobs:
         id: git_info
         if: startsWith(github.ref, 'refs/tags/')
         run: echo "::set-output name=tag::${GITHUB_REF##*/}"
-      - name: Get project info
+      - name: Decide image tag name
         id: determine
         env:
           git_tag: ${{ steps.git_info.outputs.tag }}
@@ -75,25 +60,19 @@ jobs:
           repo="${GITHUB_REPOSITORY,,}"  # to lower case
           # if build triggered by tag, use tag name
           tag="${git_tag:-latest}"
-
-          # if tag is a version number prefixed by 'v', remove the 'v'
-          if [[ "$tag" =~ ^v[0-9].* ]]; then
-            tag="${tag:1}"
-          fi
-
           dock_image=$repo:$tag
           echo $dock_image
           echo "::set-output name=dock_image::$dock_image"
           echo "::set-output name=repo::$repo"
+      - uses: actions/checkout@v2
 
-      - uses: actions/checkout@v3
-        # QEMU is used for non-x86_64 builds
-      - uses: docker/setup-qemu-action@v2
-        # buildx adds additional features to docker build
-      - uses: docker/setup-buildx-action@v2
+      # QEMU is for emulating non-x86_64 platforms
+      - uses: docker/setup-qemu-action@v1
+      # buildx is the next-generation docker image builder
+      - uses: docker/setup-buildx-action@v1
         with:
           driver-opts: network=host
-        # cache slightly improves rebuild time
+      # save some time during rebuilds
       - name: Cache Docker layers
         uses: actions/cache@v2
         with:
@@ -101,33 +80,31 @@ jobs:
           key: ${{ runner.os }}-buildx-${{ github.sha }}
           restore-keys: |
             ${{ runner.os }}-buildx-
-
       - name: Login to DockerHub
         id: dockerhub_login
-        uses: docker/login-action@v2
+        uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           
       - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2 
+        uses: docker/login-action@v1 
         with:
           registry: ghcr.io
           username: ${{ github.repository_owner }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build and push
-        uses: docker/build-push-action@v3
+        uses: docker/build-push-action@v2
         id: docker_build
         with:
           context: .
           file: ./Dockerfile
           tags: |
+            ${{ steps.determine.outputs.dock_image }}
             localhost:5000/${{ steps.determine.outputs.dock_image }}
-            docker.io/${{ steps.determine.outputs.dock_image }}
             ghcr.io/${{ steps.determine.outputs.dock_image }}
-          # if non-x86_84 architectures are supported, add them here
-          platforms: linux/amd64  #,linux/arm64,linux/ppc64le
+          platforms: linux/amd64
           push: true
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
@@ -137,10 +114,13 @@ jobs:
         run: |
           repo=${{ steps.determine.outputs.repo }}
           dock_image=${{ steps.determine.outputs.dock_image }}
-          docker run --rm localhost:5000/$dock_image chris_plugin_info > /tmp/description.json
-          jq < /tmp/description.json  # pretty print in log
-          echo "::set-output name=title::$(jq -r '.title' < /tmp/description.json)"
-
+          docker pull localhost:5000/$dock_image
+          docker tag localhost:5000/$dock_image $dock_image
+          script=$(docker inspect --format '{{ (index .Config.Cmd 0) }}' $dock_image)
+          json="$(docker run --rm $dock_image $script --json)"
+          jq <<< "$json"  # pretty print in log
+          echo "::set-output name=json::$json"
+          echo "::set-output name=title::$(jq -r '.title' <<< "$json")"
       - name: Update DockerHub description
         uses: peter-evans/dockerhub-description@v2
         continue-on-error: true  # it is not crucial that this works
@@ -148,12 +128,35 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
           short-description: ${{ steps.pluginmeta.outputs.title }}
-          readme-filepath: ./README.md
+          readme-filepath: ./README.rst
           repository: ${{ steps.determine.outputs.repo }}
 
       - name: Upload to ChRIS Store
-        if: github.event_name == 'release'
-        uses: FNNDSC/chrisstore-action@master
-        with:
-          descriptor_file: /tmp/description.json
-          auth: ${{ secrets.CHRIS_STORE_USER }}
+        if: "!endsWith(steps.determine.outputs.dock_image, ':latest')"
+        run: |
+          dock_image=${{ steps.determine.outputs.dock_image }}
+          plname="$(sed 's/^.*\///' <<< $GITHUB_REPOSITORY)" && echo "name=$plname"
+          descriptor_file=$(mktemp --suffix .json)
+          cat > $descriptor_file << ENDOFPLUGINJSONDESCRIPTION
+          ${{ steps.pluginmeta.outputs.json }}
+          ENDOFPLUGINJSONDESCRIPTION
+          res=$(
+            curl -s -u "${{ secrets.CHRIS_STORE_USER }}" "https://chrisstore.co/api/v1/plugins/" \
+              -H 'Accept:application/vnd.collection+json' \
+              -F "name=$plname" \
+              -F "dock_image=$dock_image"  \
+              -F "descriptor_file=@$descriptor_file" \
+              -F "public_repo=https://github.com/${{ github.repository }}"
+          )
+          success=$?
+          echo "::debug::$res"
+          if [ "$success" = "0" ]; then
+            href="$(jq -r '.collection.items[0].href' <<< "$res")"
+            echo $href
+            echo "::set-output name=pluginurl::$href"
+          else
+            echo "::error ::Failed upload to ChRIS Store"
+            echo "$res"
+            exit $success
+          fi
+
